baseURL = "http://ducoz.com"
languageCode = "en-us"
title = "Hugo ducoz theme"

theme = "ducoz"

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = "/"
    weight  = 1
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 4
# Site Params
[params]
  author = "Lerte Smith"
  description = "Ducoz Hugo Bulma theme"
  dateFormat = "8 June 2021"

  fixedTop = true