name = "Ducoz"
license = "MIT"
licenselink = "https://github.com/lerte/ducoz/blob/master/LICENSE"
description = "Hugo bootstrap5 theme"
homepage = "https://github.com/lerte/ducoz"
tags = ["bootstrap", "bootstrap5", "dark mode", "blog", "tag", "portfolio", "responsive"]
features = ["bootstrap5", "responsive", "dark mode"]
min_version = "0.54.0"

[author]
    name = "Lerte Smith"
    homepage = "https://ducoz.com"

